services:
  mcserver-web-page:
    container_name: mcserver-web-page
    build: .
    env_file: .env
    environment:
      - BACKGROUND_IMAGE_URL=${BACKGROUND_IMAGE_URL:-""}
    ports:
      - "${PORT}:${PORT}"
    volumes:
      -./data/:${DATADIR}